name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Highashikata
          outputs: svg

      - name: push snake to the main branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
